# Generated by Django 5.2.8 on 2025-11-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TenDanhMuc",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Tên Danh mục"
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ("TenDanhMuc",),
            },
        ),
        migrations.CreateModel(
            name="DiaChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ChiTietDiaChi",
                    models.CharField(max_length=255, verbose_name="Chi tiết"),
                ),
                ("Phuong_Xa", models.CharField(max_length=100)),
                ("Tinh_Thanh_Pho", models.CharField(max_length=100)),
                (
                    "SDTLienHe",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SĐT liên hệ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Địa chỉ",
                "verbose_name_plural": "Địa chỉ",
            },
        ),
        migrations.CreateModel(
            name="GiamGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MaGiamGia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã giảm giá"
                    ),
                ),
                ("TGbatDau", models.DateTimeField(verbose_name="Thời gian bắt đầu")),
                ("TGKetThuc", models.DateTimeField(verbose_name="Thời gian kết thúc")),
                (
                    "GiaTriGiam",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá trị giảm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Mã giảm giá",
            },
        ),
        migrations.CreateModel(
            name="KhuyenMai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "LoaiGiamGia",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Phần trăm (%)"),
                            ("AMOUNT", "Số tiền cố định (VNĐ)"),
                        ],
                        max_length=10,
                        verbose_name="Loại giảm giá",
                    ),
                ),
                (
                    "GiaTri",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá trị"
                    ),
                ),
                ("NgayBatDau", models.DateTimeField(verbose_name="Bắt đầu")),
                ("NgayKetThuc", models.DateTimeField(verbose_name="Kết thúc")),
            ],
            options={
                "verbose_name": "Chương trình khuyến mãi",
                "verbose_name_plural": "Chương trình khuyến mãi",
            },
        ),
        migrations.CreateModel(
            name="LoaiThuocTinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TenThuocTinh",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên Thuộc tính"
                    ),
                ),
                (
                    "DonViTinh",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Đơn vị tính"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại thuộc tính",
                "verbose_name_plural": "Loại thuộc tính",
            },
        ),
        migrations.CreateModel(
            name="PhuongThucThanhToan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TenPTTT",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên PTTT"
                    ),
                ),
            ],
            options={
                "verbose_name": "Phương thức thanh toán",
                "verbose_name_plural": "Phương thức thanh toán",
            },
        ),
        migrations.CreateModel(
            name="TaiKhoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TenKhachHang",
                    models.CharField(max_length=200, verbose_name="Tên khách hàng"),
                ),
                (
                    "SDT",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "GioiTinh",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Giới tính"
                    ),
                ),
                ("Email", models.EmailField(max_length=255, unique=True)),
                ("MatKhau", models.CharField(max_length=255)),
                (
                    "HangThanhVien",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Hạng TV"
                    ),
                ),
                ("NgaySinh", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tài khoản",
                "verbose_name_plural": "Tài khoản",
            },
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NgayDat", models.DateTimeField(auto_now_add=True)),
                (
                    "TrangThaiGH",
                    models.CharField(max_length=50, verbose_name="Trạng thái"),
                ),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "DiaChi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.diachi",
                        verbose_name="Địa chỉ giao hàng",
                    ),
                ),
                (
                    "GiamGia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.giamgia",
                    ),
                ),
                (
                    "ThanhToan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.phuongthucthanhtoan",
                    ),
                ),
                (
                    "TaiKhoan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.taikhoan",
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "ordering": ("-NgayDat",),
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TenSanPham",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tên Sản phẩm"
                    ),
                ),
                ("Slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("DonGia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "SoLuongTonKho",
                    models.IntegerField(default=0, verbose_name="Tồn kho"),
                ),
                ("MoTa", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                (
                    "ThuongHieu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thương hiệu",
                    ),
                ),
                (
                    "DanhMuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanphams",
                        to="web.danhmuc",
                        verbose_name="Danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "ordering": ("TenSanPham",),
            },
        ),
        migrations.CreateModel(
            name="HinhAnh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Anh", models.CharField(max_length=255, verbose_name="Đường dẫn ảnh")),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hinhanhs",
                        to="web.sanpham",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh",
                "verbose_name_plural": "Hình ảnh",
            },
        ),
        migrations.CreateModel(
            name="SanPham_KhuyenMai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "KhuyenMai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.khuyenmai"
                    ),
                ),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.sanpham"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liên kết KM",
                "verbose_name_plural": "Liên kết KM",
                "unique_together": {("SanPham", "KhuyenMai")},
            },
        ),
        migrations.AddField(
            model_name="sanpham",
            name="khuyen_mai",
            field=models.ManyToManyField(
                related_name="sanphams_ap_dung",
                through="web.SanPham_KhuyenMai",
                to="web.khuyenmai",
                verbose_name="Chương trình khuyến mãi",
            ),
        ),
        migrations.CreateModel(
            name="GioHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TaiKhoan",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giohang",
                        to="web.taikhoan",
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giỏ hàng",
                "verbose_name_plural": "Giỏ hàng",
            },
        ),
        migrations.AddField(
            model_name="diachi",
            name="TaiKhoan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diachis",
                to="web.taikhoan",
                verbose_name="Tài khoản",
            ),
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NoiDung", models.TextField(blank=True, null=True)),
                ("Diem", models.IntegerField(verbose_name="Điểm đánh giá")),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="web.sanpham",
                    ),
                ),
                (
                    "TaiKhoan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.taikhoan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
            },
        ),
        migrations.CreateModel(
            name="ChiTietGioHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField()),
                (
                    "GioHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web.giohang",
                    ),
                ),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.sanpham"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết giỏ hàng",
                "verbose_name_plural": "Chi tiết giỏ hàng",
                "unique_together": {("GioHang", "SanPham")},
            },
        ),
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField()),
                (
                    "DonGiaTaiThoiDiemMua",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "DonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="web.donhang",
                    ),
                ),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="web.sanpham"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Chi tiết đơn hàng",
                "unique_together": {("DonHang", "SanPham")},
            },
        ),
        migrations.CreateModel(
            name="SanPham_ThuocTinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "GiaTriThuocTinh",
                    models.CharField(max_length=255, verbose_name="Giá trị"),
                ),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thuoc_tinh",
                        to="web.sanpham",
                    ),
                ),
                (
                    "ThuocTinh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.loaithuoctinh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thuộc tính SP",
                "verbose_name_plural": "Thuộc tính SP",
                "unique_together": {("SanPham", "ThuocTinh")},
            },
        ),
    ]
