# Generated by Django 5.2.8 on 2025-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diachi",
            name="MacDinh",
            field=models.BooleanField(default=False, verbose_name="Mặc định"),
        ),
    ]
