# Generated by Django 5.2.8 on 2025-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_diachi_macdinh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietdonhang",
            name="DonGiaTaiThoiDiemMua",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="donhang",
            name="TongTien",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="giamgia",
            name="GiaTriGiam",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Giá trị giảm"
            ),
        ),
        migrations.AlterField(
            model_name="khuyenmai",
            name="GiaTri",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Giá trị"
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="DonGia",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
