# Generated by Django 5.2.8 on 2025-12-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_chitietdonhang_dongiataithoidiemmua_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donhang",
            name="TrangThaiGH",
            field=models.CharField(
                choices=[
                    ("Chờ xử lý", "Chờ xử lý"),
                    ("Đang giao", "Đang giao"),
                    ("Đã giao", "Đã giao"),
                    ("Hủy", "Hủy"),
                ],
                default="Chờ xử lý",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
    ]
