# Generated by Django 5.2.8 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_donhang_trangthaigh"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donhang",
            name="TrangThaiGH",
        ),
        migrations.AddField(
            model_name="donhang",
            name="lyDoHuy",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do hủy"),
        ),
        migrations.AddField(
            model_name="donhang",
            name="trangThaiGH",
            field=models.CharField(
                choices=[
                    ("Chờ xử lý", "Chờ xử lý"),
                    ("Đã xác nhận", "Đã xác nhận"),
                    ("Đang giao", "Đang giao"),
                    ("Đã giao", "Đã giao"),
                    ("Đã hủy", "Đã hủy"),
                ],
                default="Chờ xử lý",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
    ]
