# Generated by Django 5.2.8 on 2025-12-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_remove_donhang_trangthaigh_donhang_lydohuy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hinhanh",
            name="Anh",
            field=models.ImageField(
                upload_to="product_images", verbose_name="Ảnh sản phẩm"
            ),
        ),
    ]
