# Generated by Django 5.2.8 on 2025-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_hinhanh_anh"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaoCaoThongKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Báo Cáo Thống Kê",
                "verbose_name_plural": "Báo Cáo Thống Kê",
                "managed": False,
            },
        ),
    ]
